env:
  global:
    - CC_TEST_REPORTER_ID=ce5f507f83f26f2f115767da1427727d1894cbdbfaa91e11954aa1d49118d639

language: ruby

rvm:
  - 2.4

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
  - bundle install; rspec spec --format documentation

after_script:
- ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
